## Arithmetic Operations

These are simple operations that allow us to directly add or subract to the color intensity.

Calculates the per-element operation of two arrays. The overall effect is increasing or decreasing brightness.

In [6]:
import cv2
import numpy as np

image = cv2.imread('images/input.jpg')
cv2.imshow('original image',image)
#image = cv2.imread('images/input.jpg')

# Create a matrix of ones, then multiply it by a scaler of 100 
# This gives a matrix with same dimesions of our image with all values being 100
M = np.ones(image.shape, dtype = "uint8") * 75 

# We use this to add this matrix M, to our image
# Notice the increase in brightness
added = cv2.add(image, M)
cv2.imshow("Added", added)

# Likewise we can also subtract
# Notice the decrease in brightness
subtracted = cv2.subtract(image, M)
cv2.imshow("Subtracted", subtracted)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
M = np.ones(image.shape, dtype = "uint8") *175
M

array([[[175, 175, 175],
        [175, 175, 175],
        [175, 175, 175],
        ...,
        [175, 175, 175],
        [175, 175, 175],
        [175, 175, 175]],

       [[175, 175, 175],
        [175, 175, 175],
        [175, 175, 175],
        ...,
        [175, 175, 175],
        [175, 175, 175],
        [175, 175, 175]],

       [[175, 175, 175],
        [175, 175, 175],
        [175, 175, 175],
        ...,
        [175, 175, 175],
        [175, 175, 175],
        [175, 175, 175]],

       ...,

       [[175, 175, 175],
        [175, 175, 175],
        [175, 175, 175],
        ...,
        [175, 175, 175],
        [175, 175, 175],
        [175, 175, 175]],

       [[175, 175, 175],
        [175, 175, 175],
        [175, 175, 175],
        ...,
        [175, 175, 175],
        [175, 175, 175],
        [175, 175, 175]],

       [[175, 175, 175],
        [175, 175, 175],
        [175, 175, 175],
        ...,
        [175, 175, 175],
        [175, 175, 175],
        [175, 175, 175]]

In [5]:
image

array([[[12, 18, 31],
        [12, 18, 31],
        [11, 17, 30],
        ...,
        [21, 24, 38],
        [21, 24, 38],
        [21, 24, 38]],

       [[12, 18, 31],
        [12, 18, 31],
        [12, 18, 31],
        ...,
        [21, 24, 38],
        [21, 24, 38],
        [21, 24, 38]],

       [[12, 18, 31],
        [12, 18, 31],
        [12, 18, 31],
        ...,
        [21, 24, 38],
        [21, 24, 38],
        [21, 24, 38]],

       ...,

       [[ 4,  7, 12],
        [ 4,  7, 12],
        [ 3,  7, 12],
        ...,
        [18, 23, 38],
        [19, 24, 39],
        [20, 25, 40]],

       [[ 3,  6, 11],
        [ 3,  6, 11],
        [ 3,  6, 11],
        ...,
        [18, 23, 38],
        [19, 24, 39],
        [20, 25, 40]],

       [[ 3,  6, 11],
        [ 3,  6, 11],
        [ 2,  5, 10],
        ...,
        [18, 23, 38],
        [18, 23, 38],
        [19, 24, 39]]], dtype=uint8)

In [9]:
subtracted

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [10]:
added

array([[[ 87,  93, 106],
        [ 87,  93, 106],
        [ 86,  92, 105],
        ...,
        [ 96,  99, 113],
        [ 96,  99, 113],
        [ 96,  99, 113]],

       [[ 87,  93, 106],
        [ 87,  93, 106],
        [ 87,  93, 106],
        ...,
        [ 96,  99, 113],
        [ 96,  99, 113],
        [ 96,  99, 113]],

       [[ 87,  93, 106],
        [ 87,  93, 106],
        [ 87,  93, 106],
        ...,
        [ 96,  99, 113],
        [ 96,  99, 113],
        [ 96,  99, 113]],

       ...,

       [[ 79,  82,  87],
        [ 79,  82,  87],
        [ 78,  82,  87],
        ...,
        [ 93,  98, 113],
        [ 94,  99, 114],
        [ 95, 100, 115]],

       [[ 78,  81,  86],
        [ 78,  81,  86],
        [ 78,  81,  86],
        ...,
        [ 93,  98, 113],
        [ 94,  99, 114],
        [ 95, 100, 115]],

       [[ 78,  81,  86],
        [ 78,  81,  86],
        [ 77,  80,  85],
        ...,
        [ 93,  98, 113],
        [ 93,  98, 113],
        [ 94,  99, 114]]

In [13]:
image

array([[[12, 18, 31],
        [12, 18, 31],
        [11, 17, 30],
        ...,
        [21, 24, 38],
        [21, 24, 38],
        [21, 24, 38]],

       [[12, 18, 31],
        [12, 18, 31],
        [12, 18, 31],
        ...,
        [21, 24, 38],
        [21, 24, 38],
        [21, 24, 38]],

       [[12, 18, 31],
        [12, 18, 31],
        [12, 18, 31],
        ...,
        [21, 24, 38],
        [21, 24, 38],
        [21, 24, 38]],

       ...,

       [[ 4,  7, 12],
        [ 4,  7, 12],
        [ 3,  7, 12],
        ...,
        [18, 23, 38],
        [19, 24, 39],
        [20, 25, 40]],

       [[ 3,  6, 11],
        [ 3,  6, 11],
        [ 3,  6, 11],
        ...,
        [18, 23, 38],
        [19, 24, 39],
        [20, 25, 40]],

       [[ 3,  6, 11],
        [ 3,  6, 11],
        [ 2,  5, 10],
        ...,
        [18, 23, 38],
        [18, 23, 38],
        [19, 24, 39]]], dtype=uint8)